#!/usr/bin/env php
<?php
/**
 * Phanbook : Delightfully simple forum and Q&A software
 *
 * Licensed under The GNU License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link    http://phanbook.com Phanbook Project
 * @since   1.0.0
 * @author  Phanbook <hello@phanbook.com>
 * @license http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 */

/**
 * A CLI launcher and a CLI script that launches Phalcon tasks
 *
 * @example cli [task] [action] [param1 [param2 ...]]
 * @example cli Example index
 * @example cli Example index --debug --single --no-record
 */

use Phanbook\Tools\Cli\PhpError;
use Phalcon\Di\FactoryDefault\Cli;
use Phanbook\Console as ConsoleApp;

// Register The Auto Loader
require __DIR__ . '/bootstrap/autoloader.php';

date_default_timezone_set('UTC');

// Capture runtime errors
register_shutdown_function([PhpError::class, 'runtimeShutdown']);

try {
    $app = new ConsoleApp( new Cli());
    // Record any php warnings/errors
    set_error_handler([PhpError::class, 'errorHandler']);

    // Check if only run single instance
    if ($key = array_search('--single', $argv)) {
        $app->setSingleInstance(true);
        // Ensure pid removes even on fatal error
        register_shutdown_function([$app, 'removeProcessInstance']);
    }

    // Check if logging to database
    if ($key = array_search('--record', $argv)) {
        $app->setRecording(true);
    }

    // Check if debug mode
    if ($key = array_search('--debug', $argv)) {
        $app->setDebug(true);
        // @TODO: later
        // Ensure debug display even on fatal error
        //register_shutdown_function([new Events\Cli\Debug(FALSE), 'display'], $app);
    }

    $app->setArgs($argv, $argc);

    // Boom, Run
    $app->run();
} catch (Exception $e) {
    echo $e;
    exit(255);
}

function d($object, $kill = true)
{
    var_export($object);
    if ($kill) {
        exit;
    }
}
/**
 * Fix undefined function t when save object which is have method
 * Validate in model
 *
 */
function t($string)
{
    //nothing
}
